import type { Category } from "./types";

export const APP_NAME = "GMAX";
export const APP_TAGLINE = "YOUR MUSIC. YOUR WAY.";
export const APP_VERSION = "1.1.0";

export const BROWSE_CATEGORIES: Category[] = [
  { id: "c1", name: "Charts", color: "#3d9a68", query: "top hits this week" },
  { id: "c2", name: "New Releases", color: "#6b7c93", query: "new music releases" },
  { id: "c3", name: "Moods", color: "#c4785a", query: "chill mood playlist" },
  { id: "c4", name: "Indian", color: "#b08a3a", query: "bollywood hits" },
  { id: "c5", name: "Hip-Hop", color: "#4a7aa3", query: "hip hop essentials" },
  { id: "c6", name: "Pop", color: "#c46b8a", query: "pop hits" },
  { id: "c7", name: "EDM", color: "#3aa8ad", query: "edm dance mix" },
  { id: "c8", name: "Rock", color: "#a34545", query: "rock classics" },
];

/** One-tap auto playlists — primary + extraQueries → long scrollable mix. */
export const AUTO_PLAYLISTS: {
  id: string;
  name: string;
  color: string;
  query: string;
  description: string;
  extraQueries?: string[];
}[] = [
  {
    id: "auto-punjabi",
    name: "Mega Punjabi Hits",
    color: "#e8b84a",
    query: "punjabi hits songs",
    description: "Biggest Punjabi hits",
    extraQueries: [
      "Diljit Dosanjh hits",
      "Sidhu Moose Wala best songs",
      "Shubh punjabi songs",
      "AP Dhillon hits",
      "Karan Aujla songs",
      "Guru Randhawa hits",
      "Yo Yo Honey Singh hits",
      "Ammy Virk punjabi",
      "Jass Manak songs",
      "Parmish Verma hits",
      "Brown Rang Honey Singh",
      "Excuses AP Dhillon",
      "Lover Diljit Dosanjh",
      "So High Sidhu Moose Wala",
      "No Love Shubh",
      "8 Parche Baani Sandhu",
      "With You AP Dhillon",
      "Insane AP Dhillon",
      "Softly Karan Aujla",
      "East Side Flow Sidhu",
    ],
  },
  {
    id: "auto-hindi",
    name: "Hindi Hits",
    color: "#e07a5f",
    query: "bollywood hindi hits",
    description: "Bollywood",
    extraQueries: [
      "Arijit Singh hits",
      "Shreya Ghoshal songs",
      "Jubin Nautiyal hits",
      "Neha Kakkar songs",
      "Atif Aslam hits",
      "Pritam bollywood hits",
      "A.R. Rahman songs",
      "Kishore Kumar classics",
      "latest bollywood songs",
      "bollywood party hits",
      "romantic bollywood songs",
      "hindi chartbusters",
      "T-Series hindi hits",
      "Bollywood 2023 2024 hits",
    ],
  },
  {
    id: "auto-love",
    name: "Love Songs",
    color: "#e056a0",
    query: "romantic love songs hindi",
    description: "Romantic",
    extraQueries: [
      "Arijit Singh romantic songs",
      "bollywood love songs",
      "slow romantic hindi",
      "punjabi love songs",
      "Atif Aslam romantic",
      "heart touching love songs",
      "tum hi ho arijit",
      "romantic ballads hindi",
      "love mashup bollywood",
      "soft love songs indian",
      "pehla nasha",
      "tujhe dekha to ye jana",
    ],
  },
  {
    id: "auto-lofi",
    name: "Lo-fi Chill",
    color: "#7c9cbf",
    query: "lofi chill beats",
    description: "Study & chill",
    extraQueries: [
      "lofi hip hop beats",
      "study lofi music",
      "chill lofi mix",
      "rain lofi beats",
      "night lofi playlist",
      "aesthetic lofi",
      "japanese lofi",
      "lofi piano chill",
      "sleep lofi beats",
      "coffee shop lofi",
      "relaxing lofi instrumental",
    ],
  },
  {
    id: "auto-funk",
    name: "Funk & Groove",
    color: "#c45c26",
    query: "funk groove songs",
    description: "Funk",
    extraQueries: [
      "classic funk hits",
      "james brown funk",
      "disco funk party",
      "70s funk music",
      "modern funk songs",
      "groove soul funk",
      "bruno mars funk",
      "funk bass groove",
      "get down funk",
      "funky dance hits",
    ],
  },
  {
    id: "auto-phonk",
    name: "Phonk",
    color: "#6b4ce6",
    query: "phonk drift music",
    description: "Drift phonk",
    extraQueries: [
      "drift phonk mix",
      "brazilian phonk",
      "aggressive phonk",
      "phonk bass boosted",
      "night drive phonk",
      "memphis phonk",
      "phonk gym workout",
      "slowed phonk",
      "phonk 2024",
      "cowbell phonk",
    ],
  },
  {
    id: "auto-hiphop",
    name: "Hip-Hop",
    color: "#4a7aa3",
    query: "hip hop rap hits",
    description: "Rap & hip-hop",
    extraQueries: [
      "drake hits",
      "kendrick lamar songs",
      "travis scott hits",
      "eminem best songs",
      "kanye west hits",
      "j cole songs",
      "trap hip hop hits",
      "old school hip hop",
      "rap chart 2024",
      "nicki minaj hits",
      "lil baby songs",
      "post malone hits",
    ],
  },
  {
    id: "auto-edm",
    name: "EDM Party",
    color: "#3aa8ad",
    query: "edm dance party mix",
    description: "Dance",
    extraQueries: [
      "martin garrix hits",
      "calvin harris songs",
      "avicii best songs",
      "david guetta hits",
      "swedish house mafia",
      "edm festival mix",
      "progressive house hits",
      "big room edm",
      "tiesto club hits",
      "marshmello songs",
      "the chainsmokers hits",
    ],
  },
  {
    id: "auto-sad",
    name: "Sad Songs",
    color: "#6b7c93",
    query: "sad emotional songs hindi",
    description: "Heartbreak",
    extraQueries: [
      "sad arijit singh songs",
      "heartbreak bollywood",
      "emotional hindi songs",
      "sad punjabi songs",
      "breakup songs hindi",
      "alone sad songs",
      "crying songs bollywood",
      "painful love songs hindi",
      "sad lofi hindi",
      "rahat fateh ali khan sad",
    ],
  },
  {
    id: "auto-party",
    name: "Party Mix",
    color: "#d4a017",
    query: "party dance bollywood",
    description: "Party",
    extraQueries: [
      "bollywood party songs",
      "punjabi party hits",
      "dance floor bollywood",
      "badshah party songs",
      "yo yo honey singh party",
      "desi party mix",
      "wedding party bollywood",
      "club bollywood hits",
      "item songs bollywood",
      "bhangra party mix",
    ],
  },
  {
    id: "auto-english",
    name: "English Pop",
    color: "#c46b8a",
    query: "english pop hits 2024",
    description: "Pop",
    extraQueries: [
      "taylor swift hits",
      "the weeknd songs",
      "dua lipa hits",
      "ed sheeran best songs",
      "ariana grande hits",
      "billie eilish songs",
      "justin bieber hits",
      "olivia rodrigo songs",
      "harry styles hits",
      "pop hits 2023 2024",
      "top 40 pop songs",
    ],
  },
  {
    id: "auto-ghazal",
    name: "Ghazal / Soft",
    color: "#8b7355",
    query: "ghazal soft hindi songs",
    description: "Soft",
    extraQueries: [
      "jagjit singh ghazal",
      "ghulam ali ghazal",
      "soft hindi classical",
      "sufi songs hindi",
      "nusrat fateh ali khan",
      "peaceful indian songs",
      "melody soft bollywood",
      "unplugged hindi songs",
      "soft acoustic hindi",
      "evening ghazal mix",
    ],
  },
];

export const ACTION_QUERIES: Record<string, string[]> = {
  discover: [
    "trending songs this week",
    "viral hits right now",
    "top global chart songs",
    "new music this month",
    "most played songs today",
  ],
  chill: [
    "Dean Luffy hindi songs",
    "Dean and Luffy indian chill",
    "Luffy hindi soft songs",
    "Dean Luffy bollywood chill",
    "indian lofi Luffy Dean",
    "hindi chill Dean Luffy mix",
    "Dean Luffy romantic hindi",
    "soft indian songs Luffy style",
  ],
  focus: [
    "Sidhu Moose Wala hits",
    "Sidhu Moose Wala best songs",
    "Shubh punjabi songs",
    "Shubh hits punjabi",
    "punjabi hits Sidhu Moose Wala",
    "top punjabi songs Sidhu Shubh",
    "Sidhu Moosewala latest",
    "punjabi focus workout Sidhu",
  ],
};

export function randomQueryFor(actionId: string): string | null {
  const pool = ACTION_QUERIES[actionId];
  if (!pool?.length) return null;
  return pool[Math.floor(Math.random() * pool.length)] ?? null;
}

export const FEATURED_QUERY = "calm ambient evening";
